### ISSUE TITLE
Wrap output in parenthesis

### ISSUE THREAD

**Issue by jgierer12** [ifiokjr/json.macro#1]
Wouldn't wrapping the macro output in parenthesis `()` largely solve the pitfall you describe in the readme?

For example,

```js
const helloWorld = { hello: 'world' }.hello;
```

isn't valid JS but

```js
const helloWorld = ({ hello: 'world' }).hello;
```

is and works as expected.

**Comment by ifiokjr** [comment]
I had tried, babel seems to remove the brackets. I couldn't figure out how to get it to stop, so just added the warning. 

I thought about an ugly hack of wrapping the `json` in an array and referencing the first item

```js
const helloWorld = [{ hello: 'world' }][0].hello;
```

This is valid, but very ugly and I'm not sure of the performance implications for larger pieces of data. 

I don't know babel very well, this is my first plugin, so it's probably a simple fix that I'm not aware of. 

Any idea how this can be done?
